services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secretadmin
      MYSQL_DATABASE: sweetwater_db
      MYSQL_USER: sweetwater_user
      MYSQL_PASSWORD: sweetwater_pass
    ports:
      - "9906:3306"
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d:z
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "sweetwater_user", "-psweetwater_pass"]
      timeout: 20s
      retries: 10
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: php_sweetwater
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/var/www/html/:z
      - vendor:/var/www/html/vendor
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    environment:
      - DB_HOST=db
      - DB_USER=sweetwater_user
      - DB_PASS=sweetwater_pass
      - DB_NAME=sweetwater_db

volumes:
  vendor:
